# Conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/evapet_db
spring.datasource.username=postgres
spring.datasource.password=eduardopst

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

# Nombre de la app
spring.application.name=evapet